### ISSUE TITLE
rails db:migrate throws an error

### ISSUE THREAD

**Issue by imulic** [mhartl/action_cable_chat_app#57]
Hi, 

I am trying to follow the steps to get started with action_cable_chat_app but I am having trouble...

when I run rails db:migrate I am getting this error.

```
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
rails aborted!
ArgumentError: wrong number of arguments (given 3, expected 2)
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/actionpack-5.2.5/lib/action_dispatch/middleware/static.rb:111:in `initialize'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/actionpack-5.2.5/lib/action_dispatch/middleware/stack.rb:37:in `new'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/actionpack-5.2.5/lib/action_dispatch/middleware/stack.rb:37:in `build'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/actionpack-5.2.5/lib/action_dispatch/middleware/stack.rb:101:in `block in build'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/actionpack-5.2.5/lib/action_dispatch/middleware/stack.rb:101:in `each'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/actionpack-5.2.5/lib/action_dispatch/middleware/stack.rb:101:in `inject'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/actionpack-5.2.5/lib/action_dispatch/middleware/stack.rb:101:in `build'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/engine.rb:510:in `block in app'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/engine.rb:506:in `synchronize'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/engine.rb:506:in `app'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `instance_exec'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `run'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/initializable.rb:60:in `run_initializers'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/application.rb:361:in `initialize!'
/Users/irfan.mulic/git/rails/action_cable_chat_app/config/environment.rb:5:in `<top (required)>'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/application.rb:337:in `require'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/application.rb:337:in `require_environment!'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/irfan.mulic/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/command.rb:48:in `invoke'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
/Users/irfan.mulic/git/rails/action_cable_chat_app/bin/rails:9:in `require'
/Users/irfan.mulic/git/rails/action_cable_chat_app/bin/rails:9:in `<top (required)>'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
/Users/irfan.mulic/.rvm/gems/ruby-3.2.2/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/irfan.mulic/git/rails/action_cable_chat_app/bin/spring:13:in `require'
/Users/irfan.mulic/git/rails/action_cable_chat_app/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
```

Please let me know what am I doing wrong

**Comment by jonnyallred** [comment]
I get the same error.
